add main domain index, add certbot, nginx-reloader for https certificates

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -33,13 +33,49 @@ services:
         VITE__CLEANUP_INTERVAL_DAYS: ${VITE__CLEANUP_INTERVAL_DAYS}
     env_file:
       - .env
+    volumes:
+      - ./nginx/logs:/var/log/nginx               # Logs for fail2ban
+      - ./certbot/www:/var/www/certbot            # Certbot HTTP challenge
+      - ./certbot/conf:/etc/letsencrypt           # SSL certificates
     ports:
-      - "127.0.0.1:80:80"
+      - "80:80"
+      - "443:443"
     depends_on:
       - wordle_backend
+      - certbot
     restart: always
     networks:
       - internal
+    
+  certbot:
+    image: certbot/certbot:latest
+    volumes:
+      - ./certbot/www:/var/www/certbot
+      - ./certbot/conf:/etc/letsencrypt
+    entrypoint: >
+      /bin/sh -c '
+        trap "exit" TERM INT;
+        while :; do
+          certbot renew --webroot -w /var/www/certbot ;
+          sleep 12h &
+          wait $!;
+        done
+      '
+      
+  nginx-reloader:
+    image: docker:cli
+    volumes:
+      - /var/run/docker.sock:/var/run/docker.sock
+    entrypoint: >
+      /bin/sh -c '
+        trap "exit" TERM INT;
+        while :; do
+          docker kill -s HUP wordle_frontend_nginx || true;
+          sleep 12h &
+          wait $!;
+        done
+      '
+
       
 networks:
   internal:
